import io
import json
import os
import numpy as np
import pandas as pd
from flask import Flask, jsonify, request
from flask_cors import CORS

app = Flask(__name__)
CORS(app)


# Custom serializer helper to force absolutely any weird data type into text/numbers safely
def safe_json_serializer(obj):
    if isinstance(obj, (pd.Timestamp, np.datetime64)):
        return obj.strftime("%Y-%m-%d %H:%M:%S")
    if isinstance(obj, (np.integer, np.int64, np.int32)):
        return int(obj)
    if isinstance(obj, (np.floating, np.float64, np.float32)):
        if np.isnan(obj) or np.isinf(obj):
            return ""  # Turn broken math errors into clean blank spaces
        return float(obj)
    if isinstance(obj, (bytes, bytearray)):
        return obj.decode("utf-8", errors="ignore")
    return str(obj)


@app.route("/parse-excel", methods=["POST"])
def parse_excel():
    try:
        if "file" not in request.files:
            return jsonify({"error": "No file part in the request"}), 400

        file = request.files["file"]
        if file.filename == "":
            return jsonify({"error": "No selected file"}), 400

        file_bytes = file.read()
        file_stream = io.BytesIO(file_bytes)

        # 1. Open the file trying both modern and legacy layout structures automatically
        try:
            df = pd.read_excel(file_stream, engine="openpyxl")
        except Exception:
            file_stream.seek(0)
            try:
                df = pd.read_excel(file_stream, engine="xlrd")
            except Exception as engine_error:
                return (
                    jsonify(
                        {
                            "error": f"Unsupported or corrupted file format. Details: {str(engine_error)}"
                        }
                    ),
                    400,
                )

        # 2. Universal Data Sanitization Layer
        # Cleans out unnamed placeholder columns generated by blank spaces
        df.columns = [
            str(col) if not str(col).startswith("Unnamed:") else f"Column {i+1}"
            for i, col in enumerate(df.columns)
        ]

        # Force convert all date and time types cleanly before processing
        for col in df.columns:
            if pd.api.types.is_datetime64_any_dtype(df[col]):
                df[col] = df[col].dt.strftime("%Y-%m-%d %H:%M:%S")

        # Replace all NaN (Not a Number), Null, Inf, and missing values with an empty string
        df = df.replace([np.inf, -np.inf], np.nan)
        df_cleaned = df.fillna("")

        headers = list(df_cleaned.columns)
        rows_list = df_cleaned.to_dict(orient="records")

        # 3. Safe, error-proof JSON compression output
        stringified_rows = json.dumps(rows_list, default=safe_json_serializer)

        return (
            jsonify({"headers": headers, "rows_json": stringified_rows}),
            200,
        )

    except Exception as e:
        return jsonify({"error": f"Internal processing crash: {str(e)}"}), 500


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
